import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { TestBed } from '@angular/core/testing';
import { provideHttpClient } from '@angular/common/http';
import {
  provideHttpClientTesting,
  HttpTestingController,
} from '@angular/common/http/testing';

import { AiTransparencyService } from './ai-transparency.service';
import { environment } from '../../../environments/environment';
import type {
  AiAcknowledgeResponse,
  AiTransparencyStatus,
} from './ai-transparency.model';

/**
 * AiTransparencyService spec — ADR-225 (EU AI Act Art 50 + IMDA MGF).
 *
 * Strict TDD per chora-web CLAUDE.md §6 — `httpMock.verify()` in afterEach;
 * exact-path assertion; success / 400 GOV_TRANSPARENCY_INVALID / 503
 * GOV_TRANSPARENCY_UNAVAILABLE / 401 branches; acknowledge idempotency +
 * disclosureVersion/locale back-fill + mustAcknowledge local echo.
 *
 * The disclosure endpoint is camelCase over the BFF (unlike the snake_case
 * learner-economy contracts).
 */

const BASE = `${environment.bffBaseUrl}/api/v1/me/ai-transparency`;

function buildStatus(
  overrides: Partial<AiTransparencyStatus> = {},
): AiTransparencyStatus {
  return {
    mustAcknowledge: true,
    currentVersion: '2026-07-07',
    acknowledgedVersion: null,
    disclosure: {
      version: '2026-07-07',
      locale: 'en',
      audienceVariant: 'standard',
      notice: {
        title: 'Meet your AI companion',
        body: 'Your Familiar is powered by AI. Replies may be imperfect.',
        action: 'Got it',
      },
      badge: {
        label: 'AI companion',
        tooltip: 'Responses here are generated by AI.',
      },
      inlineLabels: {
        aiGenerated: { label: 'AI-generated', tooltip: 'Created by AI.' },
        aiAssisted: { label: 'AI-assisted', tooltip: 'Drafted with AI help.' },
        doseHeader: {
          label: 'AI-composed dose',
          tooltip: 'Today’s dose was composed by AI.',
        },
      },
    },
    ...overrides,
  };
}

function buildAck(
  overrides: Partial<AiAcknowledgeResponse> = {},
): AiAcknowledgeResponse {
  return {
    acknowledged: true,
    disclosureVersion: '2026-07-07',
    acknowledgedAt: '2026-07-07T10:00:00Z',
    minorMode: false,
    ...overrides,
  };
}

function setup(): {
  service: AiTransparencyService;
  httpMock: HttpTestingController;
} {
  TestBed.configureTestingModule({
    providers: [provideHttpClient(), provideHttpClientTesting()],
  });
  return {
    service: TestBed.inject(AiTransparencyService),
    httpMock: TestBed.inject(HttpTestingController),
  };
}

describe('AiTransparencyService (ADR-225 notice-only transparency)', () => {
  let service: AiTransparencyService;
  let httpMock: HttpTestingController;

  beforeEach(() => {
    ({ service, httpMock } = setup());
  });

  afterEach(() => {
    httpMock.verify();
  });

  describe('getTransparency', () => {
    it('GETs the locale-scoped disclosure and exposes signals on success', () => {
      service.getTransparency('en');
      const req = httpMock.expectOne(`${BASE}?locale=en`);
      expect(req.request.method).toBe('GET');
      req.flush(buildStatus());

      expect(service.loadState().status).toBe('success');
      expect(service.transparency()?.currentVersion).toBe('2026-07-07');
      expect(service.disclosure()?.badge.label).toBe('AI companion');
      expect(service.mustAcknowledge()).toBe(true);
    });

    it('passes the given locale through as a query param', () => {
      service.getTransparency('zh-CN');
      const req = httpMock.expectOne(`${BASE}?locale=zh-CN`);
      expect(req.request.method).toBe('GET');
      req.flush(buildStatus({ acknowledgedVersion: null }));
    });

    it('sets loading before the response resolves', () => {
      service.getTransparency('en');
      expect(service.loadState().status).toBe('loading');
      const req = httpMock.expectOne(`${BASE}?locale=en`);
      req.flush(buildStatus());
    });

    it('mustAcknowledge is false when the BE says already acknowledged', () => {
      service.getTransparency('en');
      httpMock
        .expectOne(`${BASE}?locale=en`)
        .flush(buildStatus({ mustAcknowledge: false, acknowledgedVersion: '2026-07-07' }));
      expect(service.mustAcknowledge()).toBe(false);
    });

    it('maps 503 GOV_TRANSPARENCY_UNAVAILABLE to a fail-loud error state', () => {
      service.getTransparency('en');
      httpMock.expectOne(`${BASE}?locale=en`).flush(
        { code: 'GOV_TRANSPARENCY_UNAVAILABLE', message: 'unavailable' },
        { status: 503, statusText: 'Service Unavailable' },
      );
      const s = service.loadState();
      expect(s.status).toBe('error');
      expect(service.disclosure()).toBeNull();
      expect(service.mustAcknowledge()).toBe(false);
    });

    it('maps 400 GOV_TRANSPARENCY_INVALID to an error state (never fabricates a disclosure)', () => {
      service.getTransparency('en');
      httpMock.expectOne(`${BASE}?locale=en`).flush(
        { code: 'GOV_TRANSPARENCY_INVALID', message: 'bad locale' },
        { status: 400, statusText: 'Bad Request' },
      );
      expect(service.loadState().status).toBe('error');
      expect(service.disclosure()).toBeNull();
    });

    it('maps 401/403 to an error state', () => {
      service.getTransparency('en');
      httpMock
        .expectOne(`${BASE}?locale=en`)
        .flush({ code: 'UNAUTHORISED', message: 'no' }, { status: 401, statusText: 'Unauthorized' });
      expect(service.loadState().status).toBe('error');
    });

    it('maps a non-503 5xx to an upstream error state', () => {
      service.getTransparency('en');
      httpMock
        .expectOne(`${BASE}?locale=en`)
        .flush({ code: 'X', message: 'boom' }, { status: 500, statusText: 'Server Error' });
      expect(service.loadState().status).toBe('error');
    });

    it('maps a network error (no status) to a generic error state', () => {
      service.getTransparency('en');
      httpMock
        .expectOne(`${BASE}?locale=en`)
        .error(new ProgressEvent('network'));
      expect(service.loadState().status).toBe('error');
    });
  });

  describe('ensureLoaded', () => {
    it('fetches once and is idempotent across repeat calls', () => {
      service.ensureLoaded('en');
      service.ensureLoaded('en');
      // Only ONE outstanding request despite two calls.
      const req = httpMock.expectOne(`${BASE}?locale=en`);
      req.flush(buildStatus());
      httpMock.expectNone(`${BASE}?locale=en`);
    });

    it('retries after a prior load error (does not permanently suppress)', () => {
      service.ensureLoaded('en');
      httpMock.expectOne(`${BASE}?locale=en`).flush(
        { code: 'GOV_TRANSPARENCY_UNAVAILABLE', message: 'down' },
        { status: 503, statusText: 'Service Unavailable' },
      );
      expect(service.loadState().status).toBe('error');
      // A subsequent mount re-attempts the load.
      service.ensureLoaded('en');
      httpMock.expectOne(`${BASE}?locale=en`).flush(buildStatus());
      expect(service.loadState().status).toBe('success');
    });
  });

  describe('acknowledge', () => {
    beforeEach(() => {
      // Prime the loaded disclosure so version/locale back-fill has a source.
      service.getTransparency('en');
      httpMock.expectOne(`${BASE}?locale=en`).flush(buildStatus());
    });

    it('POSTs the required surface + scope and back-fills disclosureVersion + locale', () => {
      service.acknowledge({
        surface: 'familiar',
        scope: 'familiar_chat',
        firstShownAt: '2026-07-07T09:59:00Z',
      });
      const req = httpMock.expectOne(`${BASE}/acknowledge`);
      expect(req.request.method).toBe('POST');
      const body = req.request.body as Record<string, unknown>;
      expect(body['surface']).toBe('familiar');
      expect(body['scope']).toBe('familiar_chat');
      expect(body['firstShownAt']).toBe('2026-07-07T09:59:00Z');
      expect(body['disclosureVersion']).toBe('2026-07-07');
      expect(body['locale']).toBe('en');
      req.flush(buildAck(), { status: 201, statusText: 'Created' });

      expect(service.ackState().status).toBe('success');
    });

    it('flips mustAcknowledge to false after a successful acknowledge (local echo, no refetch)', () => {
      expect(service.mustAcknowledge()).toBe(true);
      service.acknowledge({ surface: 'familiar', scope: 'familiar_chat' });
      httpMock.expectOne(`${BASE}/acknowledge`).flush(buildAck(), {
        status: 201,
        statusText: 'Created',
      });
      expect(service.mustAcknowledge()).toBe(false);
    });

    it('honours a caller-supplied disclosureVersion + locale over the back-fill', () => {
      service.acknowledge({
        surface: 'familiar',
        scope: 'familiar_chat',
        disclosureVersion: 'override-v9',
        locale: 'ms-MY',
      });
      const req = httpMock.expectOne(`${BASE}/acknowledge`);
      const body = req.request.body as Record<string, unknown>;
      expect(body['disclosureVersion']).toBe('override-v9');
      expect(body['locale']).toBe('ms-MY');
      req.flush(buildAck(), { status: 201, statusText: 'Created' });
    });

    it('is idempotent — a repeat acknowledge still resolves success (201)', () => {
      service.acknowledge({ surface: 'familiar', scope: 'familiar_chat' });
      httpMock
        .expectOne(`${BASE}/acknowledge`)
        .flush(buildAck({ acknowledged: true }), { status: 201, statusText: 'Created' });
      service.acknowledge({ surface: 'familiar', scope: 'familiar_chat' });
      httpMock
        .expectOne(`${BASE}/acknowledge`)
        .flush(buildAck({ acknowledged: true }), { status: 201, statusText: 'Created' });
      expect(service.ackState().status).toBe('success');
    });

    it('maps a 400 acknowledge failure to a fail-loud error state (keeps mustAcknowledge true)', () => {
      service.acknowledge({ surface: 'familiar', scope: 'familiar_chat' });
      httpMock.expectOne(`${BASE}/acknowledge`).flush(
        { code: 'GOV_TRANSPARENCY_INVALID', message: 'bad' },
        { status: 400, statusText: 'Bad Request' },
      );
      expect(service.ackState().status).toBe('error');
      // Not acknowledged → the gate must remain up so the learner can retry.
      expect(service.mustAcknowledge()).toBe(true);
    });

    it('maps a 503 acknowledge failure to an error state', () => {
      service.acknowledge({ surface: 'familiar', scope: 'familiar_chat' });
      httpMock.expectOne(`${BASE}/acknowledge`).flush(
        { code: 'GOV_TRANSPARENCY_UNAVAILABLE', message: 'down' },
        { status: 503, statusText: 'Service Unavailable' },
      );
      expect(service.ackState().status).toBe('error');
      expect(service.mustAcknowledge()).toBe(true);
    });

    it('maps a 401 acknowledge failure to an unauthorised error state', () => {
      service.acknowledge({ surface: 'familiar', scope: 'familiar_chat' });
      httpMock
        .expectOne(`${BASE}/acknowledge`)
        .flush({ code: 'UNAUTHORISED', message: 'no' }, { status: 401, statusText: 'Unauthorized' });
      expect(service.ackState().status).toBe('error');
    });

    it('maps a non-503 5xx acknowledge failure to an upstream error state', () => {
      service.acknowledge({ surface: 'familiar', scope: 'familiar_chat' });
      httpMock
        .expectOne(`${BASE}/acknowledge`)
        .flush({ code: 'X', message: 'boom' }, { status: 500, statusText: 'Server Error' });
      expect(service.ackState().status).toBe('error');
    });

    it('clearAckState resets the acknowledge flow to idle', () => {
      service.acknowledge({ surface: 'familiar', scope: 'familiar_chat' });
      httpMock
        .expectOne(`${BASE}/acknowledge`)
        .flush({ code: 'X', message: 'boom' }, { status: 500, statusText: 'Server Error' });
      expect(service.ackState().status).toBe('error');
      service.clearAckState();
      expect(service.ackState().status).toBe('idle');
    });
  });
});
