import { Injectable } from '@angular/core';
import { ApiError } from '../interceptors/api-error.model';

export interface MappedError {
  title: string;
  message: string;
  actions?: string[];
  retryable?: boolean;
  displayPattern?: string;
}

/**
 * Maps domain error codes to i18n keys and structured user-facing errors.
 * Source of truth: chora-core/errors/catalog (Go error code registry).
 *
 * Error codes are grouped by domain and kept in sync with the backend
 * catalog definitions in chora-core/errors/catalog/codes_*.go.
 */
const ERROR_CODE_MAP: Record<string, string> = {
  // === ATOMIC ===
  ATOM_NOT_FOUND: 'errors.atomic.not_found',
  ATOM_ALREADY_ARCHIVED: 'errors.atomic.already_archived',
  ATOM_INVALID_TYPE: 'errors.atomic.invalid_type',
  ATOM_INVALID_DIFFICULTY: 'errors.atomic.invalid_difficulty',
  ATOM_REVISION_IMMUTABLE: 'errors.atomic.revision_immutable',
  ATOM_REVISION_CONTENT_REQUIRED: 'errors.atomic.revision_content_required',
  ATOM_REVISION_NOT_FOUND: 'errors.atomic.revision_not_found',
  ATOM_REVISION_DRAFT_EXISTS: 'errors.atomic.revision_draft_exists',
  ATOM_REVISION_NOT_DRAFT: 'errors.atomic.revision_not_draft',
  ATOM_TOPIC_NOT_FOUND: 'errors.atomic.topic_not_found',
  ATOM_TOPIC_CIRCULAR_REF: 'errors.atomic.topic_circular_ref',
  ATOM_TOPIC_NAME_REQUIRED: 'errors.atomic.topic_name_required',
  ATOM_TOPIC_NAME_TOO_LONG: 'errors.atomic.topic_name_too_long',
  ATOM_PATH_NOT_FOUND: 'errors.atomic.path_not_found',
  ATOM_PATH_PREREQUISITE_INCOMPLETE: 'errors.atomic.path_prerequisite_incomplete',
  ATOM_PATH_STEP_NOT_FOUND: 'errors.atomic.path_step_not_found',
  ATOM_PATH_STEP_DUPLICATE: 'errors.atomic.path_step_duplicate',
  ATOM_PATH_TITLE_REQUIRED: 'errors.atomic.path_title_required',
  ATOM_SESSION_NOT_FOUND: 'errors.atomic.session_not_found',
  ATOM_SESSION_ALREADY_STARTED: 'errors.atomic.session_already_started',
  ATOM_SESSION_ALREADY_SUBMITTED: 'errors.atomic.session_already_submitted',
  ATOM_SESSION_NOT_ACTIVE: 'errors.atomic.session_not_active',
  ATOM_SESSION_TIME_EXPIRED: 'errors.atomic.session_time_expired',
  ATOM_INVALID_SESSION_TYPE: 'errors.atomic.invalid_session_type',
  ATOM_INVALID_STRUCTURE_MODE: 'errors.atomic.invalid_structure_mode',
  ATOM_STUDY_LIST_NOT_FOUND: 'errors.atomic.study_list_not_found',
  ATOM_SHARE_CODE_NOT_FOUND: 'errors.atomic.share_code_not_found',
  ATOM_STUDY_LIST_TITLE_REQUIRED: 'errors.atomic.study_list_title_required',
  ATOM_INTERACTION_INVALID: 'errors.atomic.interaction_invalid',

  // === IAM ===
  IAM_GCID_NOT_FOUND: 'errors.iam.gcid_not_found',
  IAM_DUPLICATE_EMAIL: 'errors.iam.duplicate_email',
  IAM_INVALID_ACCOUNT_STATE: 'errors.iam.invalid_account_state',
  IAM_WEAK_PASSWORD: 'errors.iam.weak_password',
  IAM_TENANT_MEMBERSHIP_NOT_FOUND: 'errors.iam.tenant_membership_not_found',
  IAM_INVALID_MEMBERSHIP_ROLE: 'errors.iam.invalid_membership_role',
  IAM_API_KEY_EXPIRED: 'errors.iam.api_key_expired',
  IAM_API_KEY_NOT_FOUND: 'errors.iam.api_key_not_found',
  IAM_API_KEY_LIMIT_EXCEEDED: 'errors.iam.api_key_limit_exceeded',
  IAM_WEBAUTHN_CREDENTIAL_NOT_FOUND: 'errors.iam.webauthn_credential_not_found',
  IAM_WEBAUTHN_CHALLENGE_NOT_FOUND: 'errors.iam.webauthn_challenge_not_found',
  IAM_WEBAUTHN_INVALID_ATTESTATION: 'errors.iam.webauthn_invalid_attestation',
  IAM_WEBAUTHN_INVALID_ASSERTION: 'errors.iam.webauthn_invalid_assertion',
  IAM_OIDC_PROVIDER_NOT_SUPPORTED: 'errors.iam.oidc_provider_not_supported',
  IAM_OIDC_INVALID_STATE: 'errors.iam.oidc_invalid_state',
  IAM_OIDC_TOKEN_EXCHANGE_FAILED: 'errors.iam.oidc_token_exchange_failed',
  IAM_INVALID_CREDENTIALS: 'errors.iam.invalid_credentials',
  IAM_SESSION_NOT_FOUND: 'errors.iam.session_not_found',
  IAM_SESSION_EXPIRED: 'errors.iam.session_expired',
  IAM_SESSION_REVOKED: 'errors.iam.session_revoked',
  IAM_ACCOUNT_LOCKED: 'errors.iam.account_locked',
  IAM_EMAIL_VERIFICATION_NOT_FOUND: 'errors.iam.email_verification_not_found',
  IAM_EMAIL_VERIFICATION_EXPIRED: 'errors.iam.email_verification_expired',
  IAM_EMAIL_ALREADY_VERIFIED: 'errors.iam.email_already_verified',
  IAM_EMAIL_VERIFICATION_RATE_LIMITED: 'errors.iam.email_verification_rate_limited',
  IAM_ROLE_ALREADY_ASSIGNED: 'errors.iam.role_already_assigned',
  IAM_CANNOT_REVOKE_LAST_ROLE: 'errors.iam.cannot_revoke_last_role',
  IAM_ROLE_NOT_ASSIGNED: 'errors.iam.role_not_assigned',
  IAM_INSUFFICIENT_PRIVILEGES: 'errors.iam.insufficient_privileges',
  IAM_DELETION_ALREADY_REQUESTED: 'errors.iam.deletion_already_requested',
  IAM_NOT_PENDING_DELETION: 'errors.iam.not_pending_deletion',
  IAM_MERGE_NOT_FOUND: 'errors.iam.merge_not_found',
  IAM_MERGE_SELF_NOT_ALLOWED: 'errors.iam.merge_self_not_allowed',
  IAM_MERGE_ALREADY_ACTIVE: 'errors.iam.merge_already_active',
  IAM_MERGE_INVALID_STATUS: 'errors.iam.merge_invalid_status',
  IAM_MERGE_CONFLICT_UNRESOLVED: 'errors.iam.merge_conflict_unresolved',
  IAM_EXPORT_NOT_FOUND: 'errors.iam.export_not_found',
  IAM_EXPORT_NOT_READY: 'errors.iam.export_not_ready',
  IAM_EXPORT_EXPIRED: 'errors.iam.export_expired',
  IAM_MIGRATION_NOT_FOUND: 'errors.iam.migration_not_found',
  IAM_MIGRATION_CONSENT_EXPIRED: 'errors.iam.migration_consent_expired',
  IAM_MIGRATION_INVALID_STATUS: 'errors.iam.migration_invalid_status',
  IAM_CONTRACT_NOT_FOUND: 'errors.iam.contract_not_found',
  IAM_CONTRACT_ALREADY_EXISTS: 'errors.iam.contract_already_exists',
  IAM_TRANSFER_NOT_FOUND: 'errors.iam.transfer_not_found',
  IAM_TRANSFER_SELF_NOT_ALLOWED: 'errors.iam.transfer_self_not_allowed',
  IAM_TRANSFER_CONSENT_PENDING: 'errors.iam.transfer_consent_pending',

  // === TENANCY ===
  TENANCY_TENANT_NOT_FOUND: 'errors.tenancy.tenant_not_found',
  TENANCY_SUBDOMAIN_CONFLICT: 'errors.tenancy.subdomain_conflict',
  TENANCY_ENTITLEMENT_NOT_FOUND: 'errors.tenancy.entitlement_not_found',
  TENANCY_ENTITLEMENT_DUPLICATE: 'errors.tenancy.entitlement_duplicate',
  TENANCY_ENTITLEMENT_DEPENDENCY_MISSING: 'errors.tenancy.entitlement_dependency_missing',
  TENANCY_ORG_UNIT_NOT_FOUND: 'errors.tenancy.org_unit_not_found',
  TENANCY_INVITATION_NOT_FOUND: 'errors.tenancy.invitation_not_found',
  TENANCY_INVITATION_EXPIRED: 'errors.tenancy.invitation_expired',
  TENANCY_INVITATION_ALREADY_CLAIMED: 'errors.tenancy.invitation_already_claimed',
  TENANCY_GRANT_NOT_FOUND: 'errors.tenancy.grant_not_found',
  TENANCY_VALIDATION_FAILED: 'errors.tenancy.validation_failed',
  TENANCY_INSUFFICIENT_SCOPE: 'errors.tenancy.insufficient_scope',
  TENANCY_PLATFORM_OWNER_REQUIRED: 'errors.tenancy.platform_owner_required',
  TENANCY_FEATURE_FLAG_NOT_FOUND: 'errors.tenancy.feature_flag_not_found',
  TENANCY_ADD_ON_NOT_FOUND: 'errors.tenancy.add_on_not_found',
  TENANCY_COLD_STORAGE_POLICY_NOT_FOUND: 'errors.tenancy.cold_storage_policy_not_found',
  TENANCY_STORAGE_QUOTA_NOT_FOUND: 'errors.tenancy.storage_quota_not_found',
  TENANCY_STORAGE_QUOTA_EXCEEDED: 'errors.tenancy.storage_quota_exceeded',

  // === ENGAGEMENT ===
  ENGAGEMENT_DASHBOARD_NOT_FOUND: 'errors.engagement.dashboard_not_found',
  ENGAGEMENT_DAILY_DOSE_NOT_AVAILABLE: 'errors.engagement.daily_dose_not_available',
  ENGAGEMENT_DAILY_DOSE_ALREADY_COMPLETED: 'errors.engagement.daily_dose_already_completed',
  ENGAGEMENT_DAILY_DOSE_SESSION_NOT_FOUND: 'errors.engagement.daily_dose_session_not_found',
  ENGAGEMENT_ATOM_NOT_FOUND: 'errors.engagement.atom_not_found',
  ENGAGEMENT_GOAL_NOT_FOUND: 'errors.engagement.goal_not_found',
  ENGAGEMENT_GOAL_SLOTS_FULL: 'errors.engagement.goal_slots_full',
  ENGAGEMENT_GOAL_ALREADY_ACCEPTED: 'errors.engagement.goal_already_accepted',
  ENGAGEMENT_GOAL_EXPIRED: 'errors.engagement.goal_expired',
  ENGAGEMENT_GOAL_ALREADY_DECLINED: 'errors.engagement.goal_already_declined',
  ENGAGEMENT_NOTIFICATION_NOT_FOUND: 'errors.engagement.notification_not_found',
  ENGAGEMENT_VALIDATION_FAILED: 'errors.engagement.validation_failed',

  // === FAMILIAR ===
  FAMILIAR_NOT_FOUND: 'errors.familiar.not_found',
  FAMILIAR_ALREADY_EXISTS: 'errors.familiar.already_exists',
  FAMILIAR_SAFETY_BLOCKED: 'errors.familiar.safety_blocked',
  FAMILIAR_QUOTA_EXCEEDED: 'errors.familiar.quota_exceeded',
  FAMILIAR_CHAT_FAILED: 'errors.familiar.chat_failed',
  FAMILIAR_EMPTY_MESSAGE: 'errors.familiar.empty_message',
  FAMILIAR_MESSAGE_TOO_LONG: 'errors.familiar.message_too_long',
  FAMILIAR_MEMORY_NOT_FOUND: 'errors.familiar.memory_not_found',
  FAMILIAR_INVALID_EMBEDDING: 'errors.familiar.invalid_embedding',
  FAMILIAR_EMBEDDING_FAILED: 'errors.familiar.embedding_failed',
  FAMILIAR_QUERY_TOO_LONG: 'errors.familiar.query_too_long',
  FAMILIAR_GOVERNANCE_CHECK_FAILED: 'errors.familiar.governance_check_failed',
  FAMILIAR_GOVERNANCE_BLOCKED: 'errors.familiar.governance_blocked',
  FAMILIAR_GOVERNANCE_MODIFIED: 'errors.familiar.governance_modified',
  FAMILIAR_MODEL_UNAVAILABLE: 'errors.familiar.model_unavailable',
  FAMILIAR_MODEL_NOT_AVAILABLE: 'errors.familiar.model_not_available',
  FAMILIAR_INVALID_TASK_TYPE: 'errors.familiar.invalid_task_type',
  FAMILIAR_UNSUPPORTED_PROVIDER: 'errors.familiar.unsupported_provider',
  FAMILIAR_TOKEN_QUOTA_EXCEEDED: 'errors.familiar.token_quota_exceeded',
  FAMILIAR_LLM_TIMEOUT: 'errors.familiar.llm_timeout',
  FAMILIAR_INVALID_STAT_VALUE: 'errors.familiar.invalid_stat_value',
  FAMILIAR_STAT_SUM_EXCEEDED: 'errors.familiar.stat_sum_exceeded',
  FAMILIAR_INVALID_PERSONALITY_TRAITS: 'errors.familiar.invalid_personality_traits',
  FAMILIAR_EVOLUTION_NOT_READY: 'errors.familiar.evolution_not_ready',
  FAMILIAR_READINESS_NO_DATA: 'errors.familiar.readiness_no_data',
  FAMILIAR_REGISTRY_ENTRY_NOT_FOUND: 'errors.familiar.registry_entry_not_found',
  FAMILIAR_REGISTRY_DUPLICATE_VERSION: 'errors.familiar.registry_duplicate_version',
  FAMILIAR_FORBIDDEN: 'errors.familiar.forbidden',
  FAMILIAR_UNAUTHORIZED: 'errors.familiar.unauthorized',
  FAMILIAR_VALIDATION_FAILED: 'errors.familiar.validation_failed',

  // === GOVERNANCE ===
  GOVERNANCE_RESTRICTION_NOT_FOUND: 'errors.governance.restriction_not_found',
  GOVERNANCE_APPEAL_NOT_FOUND: 'errors.governance.appeal_not_found',
  GOVERNANCE_APPEAL_COOLDOWN: 'errors.governance.appeal_cooldown',
  GOVERNANCE_KYC_PENDING: 'errors.governance.kyc_pending',
  GOVERNANCE_KYC_NOT_FOUND: 'errors.governance.kyc_not_found',
  GOVERNANCE_RESTRICTION_ALREADY_LIFTED: 'errors.governance.restriction_already_lifted',
  GOVERNANCE_APPEAL_ALREADY_DECIDED: 'errors.governance.appeal_already_decided',
  GOVERNANCE_INVALID_TIER: 'errors.governance.invalid_tier',
  GOVERNANCE_SELF_RESTRICTION_NOT_ALLOWED: 'errors.governance.self_restriction_not_allowed',
  GOVERNANCE_MODERATION_CONTENT_NOT_FOUND: 'errors.governance.moderation_content_not_found',
  GOVERNANCE_UNAUTHORIZED: 'errors.governance.unauthorized',
  GOVERNANCE_INVALID_DOCUMENT_TYPE: 'errors.governance.invalid_document_type',
  GOVERNANCE_INVALID_APPEAL_STATUS: 'errors.governance.invalid_appeal_status',
  GOVERNANCE_INVALID_RESTRICTION_STATUS: 'errors.governance.invalid_restriction_status',
  GOVERNANCE_DUPLICATE_RESTRICTION: 'errors.governance.duplicate_restriction',
  GOVERNANCE_VALIDATION_FAILED: 'errors.governance.validation_failed',
  GOVERNANCE_NOT_FOUND: 'errors.governance.not_found',
  GOVERNANCE_FORBIDDEN: 'errors.governance.forbidden',

  // === CIRCLE ===
  CIRCLE_CONNECTION_NOT_FOUND: 'errors.circle.connection_not_found',
  CIRCLE_CONNECTION_ALREADY_EXISTS: 'errors.circle.connection_already_exists',
  CIRCLE_CONNECTION_ALREADY_ACCEPTED: 'errors.circle.connection_already_accepted',
  CIRCLE_CONNECTION_SELF_REQUEST: 'errors.circle.connection_self_request',
  CIRCLE_PLAYLIST_NOT_FOUND: 'errors.circle.playlist_not_found',
  CIRCLE_PLAYLIST_ITEM_ALREADY_EXISTS: 'errors.circle.playlist_item_already_exists',
  CIRCLE_PLAYLIST_FULL: 'errors.circle.playlist_full',
  CIRCLE_SHARE_NOT_CONNECTED: 'errors.circle.share_not_connected',
  CIRCLE_GROUP_NOT_FOUND: 'errors.circle.group_not_found',
  CIRCLE_GROUP_FULL: 'errors.circle.group_full',
  CIRCLE_GROUP_ALREADY_MEMBER: 'errors.circle.group_already_member',
  CIRCLE_CHALLENGE_NOT_FOUND: 'errors.circle.challenge_not_found',
  CIRCLE_CHALLENGE_ALREADY_ACCEPTED: 'errors.circle.challenge_already_accepted',
  CIRCLE_CHALLENGE_EXPIRED: 'errors.circle.challenge_expired',
  CIRCLE_FEED_ENTRY_NOT_FOUND: 'errors.circle.feed_entry_not_found',
  CIRCLE_REACTION_ALREADY_EXISTS: 'errors.circle.reaction_already_exists',
  CIRCLE_DUEL_NOT_FOUND: 'errors.circle.duel_not_found',
  CIRCLE_VALIDATION_FAILED: 'errors.circle.validation_failed',

  // === COMMUNITY ===
  COMMUNITY_ATOM_NOT_FOUND: 'errors.community.atom_not_found',
  COMMUNITY_REVIEW_NOT_FOUND: 'errors.community.review_not_found',
  COMMUNITY_CURATION_NOT_FOUND: 'errors.community.curation_not_found',
  COMMUNITY_CONTRIBUTOR_NOT_FOUND: 'errors.community.contributor_not_found',
  COMMUNITY_COMMENT_NOT_FOUND: 'errors.community.comment_not_found',
  COMMUNITY_DUPLICATE_VOTE: 'errors.community.duplicate_vote',
  COMMUNITY_DUPLICATE_REVIEW: 'errors.community.duplicate_review',
  COMMUNITY_SELF_REVIEW: 'errors.community.self_review',
  COMMUNITY_REVIEW_NOT_DECIDABLE: 'errors.community.review_not_decidable',
  COMMUNITY_CURATION_NOT_DECIDABLE: 'errors.community.curation_not_decidable',
  COMMUNITY_ATOM_NOT_VOTABLE: 'errors.community.atom_not_votable',
  COMMUNITY_ATOM_NOT_COMMENTABLE: 'errors.community.atom_not_commentable',
  COMMUNITY_INVALID_STATE_TRANSITION: 'errors.community.invalid_state_transition',
  COMMUNITY_VALIDATION_FAILED: 'errors.community.validation_failed',
  COMMUNITY_NOT_FOUND: 'errors.community.not_found',
  COMMUNITY_FORBIDDEN: 'errors.community.forbidden',
  COMMUNITY_UNAUTHORIZED: 'errors.community.unauthorized',

  // === GATEWAY ===
  GATEWAY_RATE_LIMIT_EXCEEDED: 'errors.gateway.rate_limit_exceeded',
  GATEWAY_SERVICE_UNAVAILABLE: 'errors.gateway.service_unavailable',
  GATEWAY_INVALID_JWT: 'errors.gateway.invalid_jwt',
  GATEWAY_JWT_EXPIRED: 'errors.gateway.jwt_expired',
  GATEWAY_MISSING_AUTH_HEADER: 'errors.gateway.missing_auth_header',
  GATEWAY_TENANT_NOT_RESOLVED: 'errors.gateway.tenant_not_resolved',
  GATEWAY_BACKEND_TIMEOUT: 'errors.gateway.backend_timeout',
  GATEWAY_ROUTE_NOT_FOUND: 'errors.gateway.route_not_found',
  GATEWAY_SEARCH_UNAVAILABLE: 'errors.gateway.search_unavailable',
  GATEWAY_SEARCH_QUERY_EMPTY: 'errors.gateway.search_query_empty',
  GATEWAY_SEARCH_QUERY_TOO_LONG: 'errors.gateway.search_query_too_long',
  GATEWAY_SEARCH_INVALID_FILTER: 'errors.gateway.search_invalid_filter',

  // === QUOTA ===
  QUOTA_TENANT_EXCEEDED: 'errors.quota.tenant_exceeded',
  QUOTA_GCID_EXCEEDED: 'errors.quota.gcid_exceeded',
  QUOTA_TOKEN_EXHAUSTED: 'errors.quota.token_exhausted',
  QUOTA_STORAGE_EXCEEDED: 'errors.quota.storage_exceeded',
  QUOTA_API_RATE_LIMITED: 'errors.quota.api_rate_limited',

  // === GENERIC ===
  GENERIC_INTERNAL_ERROR: 'errors.generic.internal_error',
  GENERIC_VALIDATION_ERROR: 'errors.generic.validation_error',
  GENERIC_NOT_FOUND: 'errors.generic.not_found',
  GENERIC_UNAUTHORIZED: 'errors.generic.unauthorized',
  GENERIC_FORBIDDEN: 'errors.generic.forbidden',
  GENERIC_CONFLICT: 'errors.generic.conflict',
  GENERIC_BAD_REQUEST: 'errors.generic.bad_request',
  GENERIC_SERVICE_UNAVAILABLE: 'errors.generic.service_unavailable',

  // === BILLING ===
  BILLING_SUBSCRIPTION_NOT_FOUND: 'errors.billing.subscription_not_found',
  BILLING_SUBSCRIPTION_ALREADY_CANCELLED: 'errors.billing.subscription_already_cancelled',
  BILLING_SUBSCRIPTION_EXPIRED: 'errors.billing.subscription_expired',
  BILLING_INVOICE_NOT_FOUND: 'errors.billing.invoice_not_found',
  BILLING_INVOICE_ALREADY_PAID: 'errors.billing.invoice_already_paid',
  BILLING_PAYMENT_NOT_FOUND: 'errors.billing.payment_not_found',
  BILLING_PAYMENT_FAILED: 'errors.billing.payment_failed',
  BILLING_DUPLICATE_PAYMENT: 'errors.billing.duplicate_payment',
  BILLING_CONTENT_PRICING_NOT_FOUND: 'errors.billing.content_pricing_not_found',
  BILLING_CONTENT_ALREADY_PRICED: 'errors.billing.content_already_priced',
  BILLING_ROYALTY_NOT_FOUND: 'errors.billing.royalty_not_found',
  BILLING_ROYALTY_SPLIT_EXCEEDS_100: 'errors.billing.royalty_split_exceeds_100',
  BILLING_MONETIZATION_POLICY_NOT_FOUND: 'errors.billing.monetization_policy_not_found',
  BILLING_PROMO_CODE_NOT_FOUND: 'errors.billing.promo_code_not_found',
  BILLING_PROMO_CODE_EXPIRED: 'errors.billing.promo_code_expired',
  BILLING_PROMO_CODE_ALREADY_REDEEMED: 'errors.billing.promo_code_already_redeemed',
  BILLING_PROMO_CODE_DUPLICATE: 'errors.billing.promo_code_duplicate',
  BILLING_PROMO_CODE_MAX_USES_REACHED: 'errors.billing.promo_code_max_uses_reached',
  BILLING_PROMO_CODE_MIN_PURCHASE_NOT_MET: 'errors.billing.promo_code_min_purchase_not_met',
  BILLING_PROMO_CODE_CONTENT_TYPE_INELIGIBLE: 'errors.billing.promo_code_content_type_ineligible',
  BILLING_PROMO_CODE_REVOKED: 'errors.billing.promo_code_revoked',
  BILLING_REFERRAL_NOT_FOUND: 'errors.billing.referral_not_found',
  BILLING_REFERRAL_ALREADY_CONVERTED: 'errors.billing.referral_already_converted',
  BILLING_REFERRAL_EXPIRED: 'errors.billing.referral_expired',
  BILLING_SELF_REFERRAL_NOT_ALLOWED: 'errors.billing.self_referral_not_allowed',
  BILLING_CAMPAIGN_NOT_FOUND: 'errors.billing.campaign_not_found',
  BILLING_CAMPAIGN_BUDGET_EXCEEDED: 'errors.billing.campaign_budget_exceeded',
  BILLING_CAMPAIGN_NOT_ACTIVE: 'errors.billing.campaign_not_active',
  BILLING_CAMPAIGN_INVALID_TRANSITION: 'errors.billing.campaign_invalid_transition',
  BILLING_NOT_FOUND: 'errors.billing.not_found',
  BILLING_FORBIDDEN: 'errors.billing.forbidden',
  BILLING_UNAUTHORIZED: 'errors.billing.unauthorized',
  BILLING_VALIDATION_FAILED: 'errors.billing.validation_failed',

  // === COMMUNICATION ===
  COMMUNICATION_NOTIFICATION_NOT_FOUND: 'errors.communication.notification_not_found',
  COMMUNICATION_NOTIFICATION_EXPIRED: 'errors.communication.notification_expired',
  COMMUNICATION_TEMPLATE_NOT_FOUND: 'errors.communication.template_not_found',
  COMMUNICATION_DUPLICATE_TEMPLATE: 'errors.communication.duplicate_template',
  COMMUNICATION_TEMPLATE_RENDER_ERROR: 'errors.communication.template_render_error',
  COMMUNICATION_TRIGGER_RULE_NOT_FOUND: 'errors.communication.trigger_rule_not_found',
  COMMUNICATION_TRIGGER_RULE_INACTIVE: 'errors.communication.trigger_rule_inactive',
  COMMUNICATION_DELIVERY_FAILED: 'errors.communication.delivery_failed',
  COMMUNICATION_NOT_FOUND: 'errors.communication.not_found',
  COMMUNICATION_FORBIDDEN: 'errors.communication.forbidden',
  COMMUNICATION_UNAUTHORIZED: 'errors.communication.unauthorized',
  COMMUNICATION_VALIDATION_FAILED: 'errors.communication.validation_failed',

  // === TRAINING ===
  TRAINING_SESSION_NOT_FOUND: 'errors.training.session_not_found',
  TRAINING_SESSION_NOT_MODIFIABLE: 'errors.training.session_not_modifiable',
  TRAINING_SESSION_NOT_DELETABLE: 'errors.training.session_not_deletable',
  TRAINING_INVALID_STATE_TRANSITION: 'errors.training.invalid_state_transition',
  TRAINING_ENROLLMENT_CLOSED: 'errors.training.enrollment_closed',
  TRAINING_SESSION_FULL: 'errors.training.session_full',
  TRAINING_DUPLICATE_APPLICATION: 'errors.training.duplicate_application',
  TRAINING_ALREADY_ENROLLED: 'errors.training.already_enrolled',
  TRAINING_APPLICATION_NOT_REVIEWABLE: 'errors.training.application_not_reviewable',
  TRAINING_REQUEST_NOT_DECIDABLE: 'errors.training.request_not_decidable',
  TRAINING_PATH_NOT_IN_PROGRAM: 'errors.training.path_not_in_program',
  TRAINING_TRANSFER_SAME_SESSION: 'errors.training.transfer_same_session',
  TRAINING_VALIDATION_FAILED: 'errors.training.validation_failed',
  TRAINING_NOT_FOUND: 'errors.training.not_found',
  TRAINING_FORBIDDEN: 'errors.training.forbidden',
  TRAINING_UNAUTHORIZED: 'errors.training.unauthorized',

  // === CAMPUS ===
  CAMPUS_TERM_NOT_FOUND: 'errors.campus.term_not_found',
  CAMPUS_VENUE_NOT_FOUND: 'errors.campus.venue_not_found',
  CAMPUS_ROOM_NOT_FOUND: 'errors.campus.room_not_found',
  CAMPUS_SECTION_NOT_FOUND: 'errors.campus.section_not_found',
  CAMPUS_BOOKING_NOT_FOUND: 'errors.campus.booking_not_found',
  CAMPUS_BOOKING_CONFLICT: 'errors.campus.booking_conflict',
  CAMPUS_SECTION_NOT_MODIFIABLE: 'errors.campus.section_not_modifiable',
  CAMPUS_INVALID_STATE_TRANSITION: 'errors.campus.invalid_state_transition',
  CAMPUS_TERM_INVALID_DATE_RANGE: 'errors.campus.term_invalid_date_range',
  CAMPUS_BOOKING_INVALID_DATE_RANGE: 'errors.campus.booking_invalid_date_range',
  CAMPUS_VALIDATION_FAILED: 'errors.campus.validation_failed',
  CAMPUS_NOT_FOUND: 'errors.campus.not_found',
  CAMPUS_FORBIDDEN: 'errors.campus.forbidden',
  CAMPUS_UNAUTHORIZED: 'errors.campus.unauthorized',

  // === CLASSROOM ===
  CLASSROOM_QUIZ_NOT_FOUND: 'errors.classroom.quiz_not_found',
  CLASSROOM_QUIZ_NOT_ACTIVE: 'errors.classroom.quiz_not_active',
  CLASSROOM_QUIZ_ALREADY_STARTED: 'errors.classroom.quiz_already_started',
  CLASSROOM_QUIZ_ALREADY_ENDED: 'errors.classroom.quiz_already_ended',
  CLASSROOM_NO_MORE_QUESTIONS: 'errors.classroom.no_more_questions',
  CLASSROOM_ALREADY_ANSWERED: 'errors.classroom.already_answered',
  CLASSROOM_ANSWER_TOO_LATE: 'errors.classroom.answer_too_late',
  CLASSROOM_PARTICIPANT_NOT_FOUND: 'errors.classroom.participant_not_found',
  CLASSROOM_POLL_NOT_FOUND: 'errors.classroom.poll_not_found',
  CLASSROOM_POLL_CLOSED: 'errors.classroom.poll_closed',
  CLASSROOM_ALREADY_VOTED: 'errors.classroom.already_voted',
  CLASSROOM_INVALID_OPTION: 'errors.classroom.invalid_option',
  CLASSROOM_BOARD_NOT_FOUND: 'errors.classroom.board_not_found',
  CLASSROOM_BOARD_CLOSED: 'errors.classroom.board_closed',
  CLASSROOM_PROFILE_NOT_FOUND: 'errors.classroom.profile_not_found',
  CLASSROOM_VALIDATION_FAILED: 'errors.classroom.validation_failed',
  CLASSROOM_INVALID_STATE_TRANSITION: 'errors.classroom.invalid_state_transition',

  // === CMS ===
  CMS_CONTENT_ITEM_NOT_FOUND: 'errors.cms.content_item_not_found',
  CMS_CONTENT_VERSION_NOT_FOUND: 'errors.cms.content_version_not_found',
  CMS_MEDIA_ASSET_NOT_FOUND: 'errors.cms.media_asset_not_found',
  CMS_PROJECT_NOT_FOUND: 'errors.cms.project_not_found',
  CMS_PROJECT_MEMBER_NOT_FOUND: 'errors.cms.project_member_not_found',
  CMS_DELIVERABLE_NOT_FOUND: 'errors.cms.deliverable_not_found',
  CMS_WORKFLOW_INVALID_TRANSITION: 'errors.cms.workflow_invalid_transition',
  CMS_VERSION_IMMUTABLE: 'errors.cms.version_immutable',
  CMS_VALIDATION_FAILED: 'errors.cms.validation_failed',
  CMS_MEDIA_SIZE_EXCEEDED: 'errors.cms.media_size_exceeded',
  CMS_MEDIA_TYPE_NOT_ALLOWED: 'errors.cms.media_type_not_allowed',
  CMS_PROJECT_MEMBER_DUPLICATE: 'errors.cms.project_member_duplicate',
  CMS_DELIVERABLE_ALREADY_GRADED: 'errors.cms.deliverable_already_graded',
  CMS_INSUFFICIENT_SCOPE: 'errors.cms.insufficient_scope',
  CMS_UNAUTHORIZED: 'errors.cms.unauthorized',
  CMS_STORAGE_QUOTA_EXCEEDED: 'errors.cms.storage_quota_exceeded',
  CMS_MEDIA_QUARANTINED: 'errors.cms.media_quarantined',
  CMS_PROCESSING_JOB_NOT_FOUND: 'errors.cms.processing_job_not_found',
  CMS_MEDIA_VARIANT_NOT_FOUND: 'errors.cms.media_variant_not_found',
  CMS_CONTENT_SCAN_RESULT_NOT_FOUND: 'errors.cms.content_scan_result_not_found',

  // === GAMIFICATION ===
  GAMIFICATION_SKIN_NOT_FOUND: 'errors.gamification.skin_not_found',
  GAMIFICATION_SKIN_ALREADY_OWNED: 'errors.gamification.skin_already_owned',
  GAMIFICATION_SKIN_NOT_EQUIPPABLE: 'errors.gamification.skin_not_equippable',
  GAMIFICATION_SLOT_ALREADY_EQUIPPED: 'errors.gamification.slot_already_equipped',
  GAMIFICATION_INSUFFICIENT_BALANCE: 'errors.gamification.insufficient_balance',
  GAMIFICATION_INSUFFICIENT_REPUTATION: 'errors.gamification.insufficient_reputation',
  GAMIFICATION_LEGENDARY_SKIN_OCCUPIED: 'errors.gamification.legendary_skin_occupied',
  GAMIFICATION_LEGENDARY_TRANSFER_FAILED: 'errors.gamification.legendary_transfer_failed',
  GAMIFICATION_BOUNTY_NOT_FOUND: 'errors.gamification.bounty_not_found',
  GAMIFICATION_BOUNTY_NOT_OPEN: 'errors.gamification.bounty_not_open',
  GAMIFICATION_BOUNTY_ALREADY_COMPLETED: 'errors.gamification.bounty_already_completed',
  GAMIFICATION_BOUNTY_SELF_SOLVE: 'errors.gamification.bounty_self_solve',
  GAMIFICATION_LEAGUE_NOT_FOUND: 'errors.gamification.league_not_found',
  GAMIFICATION_BADGE_ALREADY_EARNED: 'errors.gamification.badge_already_earned',
  GAMIFICATION_NOT_FOUND: 'errors.gamification.not_found',
  GAMIFICATION_FORBIDDEN: 'errors.gamification.forbidden',
  GAMIFICATION_UNAUTHORIZED: 'errors.gamification.unauthorized',
  GAMIFICATION_VALIDATION_FAILED: 'errors.gamification.validation_failed',

  // === MEDIA_PROCESSOR ===
  MEDIA_PROCESSOR_PROCESSING_JOB_NOT_FOUND: 'errors.media_processor.processing_job_not_found',
  MEDIA_PROCESSOR_MEDIA_ASSET_NOT_FOUND: 'errors.media_processor.media_asset_not_found',
  MEDIA_PROCESSOR_SCAN_FAILED: 'errors.media_processor.scan_failed',
  MEDIA_PROCESSOR_MODERATION_FAILED: 'errors.media_processor.moderation_failed',
  MEDIA_PROCESSOR_OPTIMIZATION_FAILED: 'errors.media_processor.optimization_failed',
  MEDIA_PROCESSOR_STORAGE_UPLOAD_FAILED: 'errors.media_processor.storage_upload_failed',
  MEDIA_PROCESSOR_STORAGE_DOWNLOAD_FAILED: 'errors.media_processor.storage_download_failed',
  MEDIA_PROCESSOR_MEDIA_QUARANTINED: 'errors.media_processor.media_quarantined',
  MEDIA_PROCESSOR_UNSUPPORTED_MIME_TYPE: 'errors.media_processor.unsupported_mime_type',
  MEDIA_PROCESSOR_QUALITY_ASSESSMENT_FAILED: 'errors.media_processor.quality_assessment_failed',

  // === SURVEY ===
  SURVEY_NOT_FOUND: 'errors.survey.not_found',
  SURVEY_NOT_MODIFIABLE: 'errors.survey.not_modifiable',
  SURVEY_NOT_PUBLISHABLE: 'errors.survey.not_publishable',
  SURVEY_NOT_PUBLISHED: 'errors.survey.not_published',
  SURVEY_ALREADY_RESPONDED: 'errors.survey.already_responded',
  SURVEY_MISSING_REQUIRED_ANSWER: 'errors.survey.missing_required_answer',
  SURVEY_NO_QUESTIONS: 'errors.survey.no_questions',
  SURVEY_TOO_MANY_QUESTIONS: 'errors.survey.too_many_questions',
  SURVEY_HAS_RESPONSES: 'errors.survey.has_responses',
  SURVEY_VALIDATION_FAILED: 'errors.survey.validation_failed',
  SURVEY_FORBIDDEN: 'errors.survey.forbidden',
  SURVEY_UNAUTHORIZED: 'errors.survey.unauthorized',

  // === WBL ===
  WBL_INTERNSHIP_NOT_FOUND: 'errors.wbl.internship_not_found',
  WBL_INTERNSHIP_NOT_OPEN: 'errors.wbl.internship_not_open',
  WBL_INTERNSHIP_FULL: 'errors.wbl.internship_full',
  WBL_DUPLICATE_APPLICATION: 'errors.wbl.duplicate_application',
  WBL_APPLICATION_NOT_REVIEWABLE: 'errors.wbl.application_not_reviewable',
  WBL_PLACEMENT_NOT_FOUND: 'errors.wbl.placement_not_found',
  WBL_PLACEMENT_NOT_ACTIVE: 'errors.wbl.placement_not_active',
  WBL_CAPSTONE_NOT_FOUND: 'errors.wbl.capstone_not_found',
  WBL_CAPSTONE_NOT_SUBMITTABLE: 'errors.wbl.capstone_not_submittable',
  WBL_NOT_MODIFIABLE: 'errors.wbl.not_modifiable',
  WBL_VALIDATION_FAILED: 'errors.wbl.validation_failed',
  WBL_NOT_FOUND: 'errors.wbl.not_found',
  WBL_FORBIDDEN: 'errors.wbl.forbidden',
  WBL_UNAUTHORIZED: 'errors.wbl.unauthorized',

  // === ANALYTICS ===
  ANALYTICS_LEARNER_NOT_FOUND: 'errors.analytics.learner_not_found',
  ANALYTICS_INSTRUCTOR_NOT_FOUND: 'errors.analytics.instructor_not_found',
  ANALYTICS_TENANT_REPORT_NOT_FOUND: 'errors.analytics.tenant_report_not_found',
  ANALYTICS_TOPIC_PERFORMANCE_NOT_FOUND: 'errors.analytics.topic_performance_not_found',
  ANALYTICS_SESSION_NOT_FOUND: 'errors.analytics.session_not_found',
  ANALYTICS_INVALID_DATE_RANGE: 'errors.analytics.invalid_date_range',
  ANALYTICS_EXPORT_FAILED: 'errors.analytics.export_failed',
  ANALYTICS_VALIDATION_FAILED: 'errors.analytics.validation_failed',
  ANALYTICS_UNAUTHORIZED: 'errors.analytics.unauthorized',
  ANALYTICS_FORBIDDEN: 'errors.analytics.forbidden',

  // === EXAM_ADMIN ===
  EXAM_ADMIN_CONTRACT_NOT_FOUND: 'errors.exam_admin.contract_not_found',
  EXAM_ADMIN_VENUE_NOT_FOUND: 'errors.exam_admin.venue_not_found',
  EXAM_ADMIN_SITTING_NOT_FOUND: 'errors.exam_admin.sitting_not_found',
  EXAM_ADMIN_SITTING_FULL: 'errors.exam_admin.sitting_full',
  EXAM_ADMIN_DUPLICATE_REGISTRATION: 'errors.exam_admin.duplicate_registration',
  EXAM_ADMIN_SITTING_NOT_STARTABLE: 'errors.exam_admin.sitting_not_startable',
  EXAM_ADMIN_SITTING_NOT_ENDABLE: 'errors.exam_admin.sitting_not_endable',
  EXAM_ADMIN_PROCTOR_SESSION_NOT_FOUND: 'errors.exam_admin.proctor_session_not_found',
  EXAM_ADMIN_RESULT_NOT_FOUND: 'errors.exam_admin.result_not_found',
  EXAM_ADMIN_INVALID_STATE_TRANSITION: 'errors.exam_admin.invalid_state_transition',
  EXAM_ADMIN_VALIDATION_FAILED: 'errors.exam_admin.validation_failed',
  EXAM_ADMIN_NOT_FOUND: 'errors.exam_admin.not_found',
  EXAM_ADMIN_FORBIDDEN: 'errors.exam_admin.forbidden',
  EXAM_ADMIN_UNAUTHORIZED: 'errors.exam_admin.unauthorized',

  // === SUPPORT ===
  SUPPORT_TICKET_NOT_FOUND: 'errors.support.ticket_not_found',
  SUPPORT_TICKET_CLOSED: 'errors.support.ticket_closed',
  SUPPORT_INVALID_STATUS_TRANSITION: 'errors.support.invalid_status_transition',
  SUPPORT_ALREADY_AT_HIGHEST_PRIORITY: 'errors.support.already_at_highest_priority',
  SUPPORT_SURVEY_ALREADY_SUBMITTED: 'errors.support.survey_already_submitted',
  SUPPORT_TICKET_NOT_RESOLVED: 'errors.support.ticket_not_resolved',
  SUPPORT_NOT_TICKET_CREATOR: 'errors.support.not_ticket_creator',
  SUPPORT_FAQ_NOT_FOUND: 'errors.support.faq_not_found',
  SUPPORT_FAQ_CATEGORY_NOT_FOUND: 'errors.support.faq_category_not_found',
  SUPPORT_VALIDATION_FAILED: 'errors.support.validation_failed',
  SUPPORT_RESPONSE_NOT_FOUND: 'errors.support.response_not_found',

  // === PARENT ===
  PARENT_LINK_NOT_FOUND: 'errors.parent.link_not_found',
  PARENT_DUPLICATE_LINK: 'errors.parent.duplicate_link',
  PARENT_LINK_ALREADY_REVOKED: 'errors.parent.link_already_revoked',
  PARENT_CONSENT_NOT_GRANTED: 'errors.parent.consent_not_granted',
  PARENT_SELF_LINK: 'errors.parent.self_link',
  PARENT_DIGEST_NOT_FOUND: 'errors.parent.digest_not_found',
  PARENT_ALERT_NOT_FOUND: 'errors.parent.alert_not_found',
  PARENT_VALIDATION_FAILED: 'errors.parent.validation_failed',
  PARENT_NOT_FOUND: 'errors.parent.not_found',
  PARENT_FORBIDDEN: 'errors.parent.forbidden',
  PARENT_UNAUTHORIZED: 'errors.parent.unauthorized',

  // === A2A_GATEWAY ===
  A2A_GATEWAY_TASK_NOT_FOUND: 'errors.a2a_gateway.task_not_found',
  A2A_GATEWAY_TASK_ALREADY_COMPLETED: 'errors.a2a_gateway.task_already_completed',
  A2A_GATEWAY_TASK_ALREADY_CANCELLED: 'errors.a2a_gateway.task_already_cancelled',
  A2A_GATEWAY_TASK_NOT_CANCELLABLE: 'errors.a2a_gateway.task_not_cancellable',
  A2A_GATEWAY_PARTNER_NOT_FOUND: 'errors.a2a_gateway.partner_not_found',
  A2A_GATEWAY_PARTNER_ALREADY_EXISTS: 'errors.a2a_gateway.partner_already_exists',
  A2A_GATEWAY_PARTNER_UNTRUSTED: 'errors.a2a_gateway.partner_untrusted',
  A2A_GATEWAY_PARTNER_REVOKED: 'errors.a2a_gateway.partner_revoked',
  A2A_GATEWAY_CONSENT_NOT_FOUND: 'errors.a2a_gateway.consent_not_found',
  A2A_GATEWAY_CONSENT_MISSING: 'errors.a2a_gateway.consent_missing',
  A2A_GATEWAY_CONSENT_EXPIRED: 'errors.a2a_gateway.consent_expired',
  A2A_GATEWAY_CONSENT_ALREADY_REVOKED: 'errors.a2a_gateway.consent_already_revoked',
  A2A_GATEWAY_AGENT_CARD_NOT_FOUND: 'errors.a2a_gateway.agent_card_not_found',
  A2A_GATEWAY_VALIDATION_FAILED: 'errors.a2a_gateway.validation_failed',
  A2A_GATEWAY_INVALID_TRUST_LEVEL: 'errors.a2a_gateway.invalid_trust_level',
};

const GENERIC_FALLBACK_KEY = 'errors.generic.unknown';

const STATUS_TITLE_MAP: Record<number, string> = {
  400: 'errors.titles.bad_request',
  401: 'errors.titles.unauthorized',
  402: 'errors.titles.payment_required',
  403: 'errors.titles.forbidden',
  404: 'errors.titles.not_found',
  409: 'errors.titles.conflict',
  410: 'errors.titles.gone',
  413: 'errors.titles.payload_too_large',
  415: 'errors.titles.unsupported_media_type',
  422: 'errors.titles.validation',
  429: 'errors.titles.rate_limited',
  500: 'errors.titles.server_error',
  502: 'errors.titles.bad_gateway',
  503: 'errors.titles.service_unavailable',
  504: 'errors.titles.gateway_timeout',
};

const STATUS_ACTION_MAP: Record<number, string[]> = {
  401: ['errors.actions.login_again'],
  402: ['errors.actions.update_payment'],
  403: ['errors.actions.contact_admin'],
  429: ['errors.actions.wait_retry'],
  500: ['errors.actions.try_again', 'errors.actions.contact_support'],
  502: ['errors.actions.try_again_later'],
  503: ['errors.actions.try_again_later'],
  504: ['errors.actions.try_again'],
};

/**
 * Maps error codes that are retryable. Kept in sync with the
 * retryable flag in chora-core/errors/catalog.
 */
const RETRYABLE_CODES = new Set<string>([
  'GENERIC_INTERNAL_ERROR',
  'GENERIC_SERVICE_UNAVAILABLE',
  'GATEWAY_RATE_LIMIT_EXCEEDED',
  'GATEWAY_SERVICE_UNAVAILABLE',
  'GATEWAY_BACKEND_TIMEOUT',
  'GATEWAY_SEARCH_UNAVAILABLE',
  'QUOTA_API_RATE_LIMITED',
  'IAM_OIDC_TOKEN_EXCHANGE_FAILED',
  'IAM_EMAIL_VERIFICATION_RATE_LIMITED',
  'IAM_EXPORT_NOT_READY',
  'FAMILIAR_QUOTA_EXCEEDED',
  'FAMILIAR_CHAT_FAILED',
  'FAMILIAR_EMBEDDING_FAILED',
  'FAMILIAR_GOVERNANCE_CHECK_FAILED',
  'FAMILIAR_MODEL_UNAVAILABLE',
  'FAMILIAR_MODEL_NOT_AVAILABLE',
  'FAMILIAR_LLM_TIMEOUT',
  'GOVERNANCE_APPEAL_COOLDOWN',
  'COMMUNICATION_TEMPLATE_RENDER_ERROR',
  'COMMUNICATION_DELIVERY_FAILED',
  'GAMIFICATION_LEGENDARY_TRANSFER_FAILED',
  'MEDIA_PROCESSOR_SCAN_FAILED',
  'MEDIA_PROCESSOR_MODERATION_FAILED',
  'MEDIA_PROCESSOR_OPTIMIZATION_FAILED',
  'MEDIA_PROCESSOR_STORAGE_UPLOAD_FAILED',
  'MEDIA_PROCESSOR_STORAGE_DOWNLOAD_FAILED',
  'MEDIA_PROCESSOR_QUALITY_ASSESSMENT_FAILED',
  'ANALYTICS_EXPORT_FAILED',
]);

@Injectable({ providedIn: 'root' })
export class ErrorMessageMapperService {
  /**
   * Maps a domain error code to its i18n translation key.
   * Returns a generic fallback key for unknown codes.
   */
  mapErrorCode(code: string): string {
    return ERROR_CODE_MAP[code] ?? GENERIC_FALLBACK_KEY;
  }

  /**
   * Returns whether an error code represents a retryable error.
   */
  isRetryable(code: string): boolean {
    return RETRYABLE_CODES.has(code);
  }

  /**
   * Maps an ApiError to a structured user-facing error with
   * title, message, optional actions, and retryable flag -- all as i18n keys.
   */
  mapApiError(error: ApiError): MappedError {
    const message = this.mapErrorCode(error.code);
    const title = STATUS_TITLE_MAP[error.status] ?? 'errors.titles.error';
    const actions = STATUS_ACTION_MAP[error.status];
    const retryable = this.isRetryable(error.code);

    return {
      title,
      message,
      retryable,
      ...(actions ? { actions } : {}),
    };
  }
}
