/**
 * Storybook stories for AiCompanionBadgeComponent (ADR-225).
 *
 * The persistent "AI companion" disclosure badge. Label + tooltip are
 * BFF-served; a stubbed AiTransparencyService supplies them. Renders nothing
 * until the disclosure loads (the "Loading (empty)" story).
 */
import type { Meta, StoryObj } from '@storybook/angular';
import { applicationConfig } from '@storybook/angular';
import { provideHttpClient } from '@angular/common/http';
import { signal } from '@angular/core';

import { AiCompanionBadgeComponent } from './ai-companion-badge.component';
import { AiTransparencyService } from '../../../core/services/ai-transparency.service';
import type { AiDisclosure } from '../../../core/services/ai-transparency.model';

function disclosure(badgeLabel: string, tooltip: string): AiDisclosure {
  return {
    version: '2026-07-07',
    locale: 'en',
    audienceVariant: 'standard',
    notice: { title: 't', body: 'b', action: 'Got it' },
    badge: { label: badgeLabel, tooltip },
    inlineLabels: {
      aiGenerated: { label: 'AI-generated', tooltip: 'x' },
      aiAssisted: { label: 'AI-assisted', tooltip: 'y' },
      doseHeader: { label: 'AI-composed dose', tooltip: 'z' },
    },
  };
}

function providers(d: AiDisclosure | null) {
  return applicationConfig({
    providers: [
      provideHttpClient(),
      {
        provide: AiTransparencyService,
        useValue: { disclosure: signal(d), ensureLoaded: () => undefined },
      },
    ],
  });
}

const meta: Meta<AiCompanionBadgeComponent> = {
  title: 'Shared/AI Transparency/CompanionBadge',
  component: AiCompanionBadgeComponent,
  parameters: {
    a11y: { element: '#storybook-root' },
    docs: {
      description: {
        component:
          'ADR-225 persistent "AI companion" badge, mounted on the Familiar ' +
          'chat header and profile. BFF-served copy, no fabricated fallback.',
      },
    },
  },
};
export default meta;
type Story = StoryObj<AiCompanionBadgeComponent>;

export const Default: Story = {
  decorators: [
    providers(disclosure('AI companion', 'Responses here are generated by AI.')),
  ],
};

export const LongTooltip: Story = {
  decorators: [
    providers(
      disclosure(
        'AI companion',
        'This companion is an AI. It generates its responses, which may be inaccurate — verify anything you rely on.',
      ),
    ),
  ],
};

/** Disclosure not yet loaded — the badge renders nothing (no fabricated copy). */
export const LoadingEmpty: Story = {
  decorators: [providers(null)],
  name: 'Loading (empty)',
};
