import { ComponentFixture, TestBed } from '@angular/core/testing';
import { signal } from '@angular/core';
import { describe, it, expect, beforeEach, vi } from 'vitest';

import { AiCompanionBadgeComponent } from './ai-companion-badge.component';
import { AiTransparencyService } from '../../../core/services/ai-transparency.service';
import type { AiDisclosure } from '../../../core/services/ai-transparency.model';

/**
 * AiCompanionBadgeComponent (ADR-225) — the persistent "AI companion" badge.
 * Renders the BFF-served `disclosure.badge` label + tooltip DIRECTLY; absent
 * (no fabricated copy) until the governance config loads.
 */

function buildDisclosure(): AiDisclosure {
  return {
    version: '2026-07-07',
    locale: 'en',
    audienceVariant: 'standard',
    notice: { title: 't', body: 'b', action: 'Got it' },
    badge: { label: 'AI companion', tooltip: 'Responses here are generated by AI.' },
    inlineLabels: {
      aiGenerated: { label: 'AI-generated', tooltip: 'x' },
      aiAssisted: { label: 'AI-assisted', tooltip: 'y' },
      doseHeader: { label: 'AI-composed dose', tooltip: 'z' },
    },
  };
}

class StubAiTransparencyService {
  readonly disclosure = signal<AiDisclosure | null>(null);
  ensureLoaded = vi.fn();
}

function setup(withDisclosure: boolean): {
  fixture: ComponentFixture<AiCompanionBadgeComponent>;
  element: HTMLElement;
  stub: StubAiTransparencyService;
} {
  const stub = new StubAiTransparencyService();
  if (withDisclosure) stub.disclosure.set(buildDisclosure());
  TestBed.configureTestingModule({
    imports: [AiCompanionBadgeComponent],
    providers: [{ provide: AiTransparencyService, useValue: stub }],
  });
  const fixture = TestBed.createComponent(AiCompanionBadgeComponent);
  fixture.detectChanges();
  return { fixture, element: fixture.nativeElement as HTMLElement, stub };
}

describe('AiCompanionBadgeComponent (ADR-225 persistent badge)', () => {
  beforeEach(() => TestBed.resetTestingModule());

  it('drives ensureLoaded on init', () => {
    const { stub } = setup(false);
    expect(stub.ensureLoaded).toHaveBeenCalled();
  });

  it('renders nothing until the disclosure loads (no fabricated copy)', () => {
    const { element } = setup(false);
    expect(element.querySelector('[data-testid="ai-companion-badge"]')).toBeNull();
  });

  it('renders the BFF badge label directly once loaded', () => {
    const { element } = setup(true);
    const badge = element.querySelector('[data-testid="ai-companion-badge"]');
    expect(badge).toBeTruthy();
    expect(badge?.textContent).toContain('AI companion');
  });

  it('exposes the BFF tooltip as the title attribute', () => {
    const { element } = setup(true);
    const badge = element.querySelector('[data-testid="ai-companion-badge"]');
    expect(badge?.getAttribute('title')).toBe('Responses here are generated by AI.');
  });

  it('has an accessible name (aria-label) so it is not icon-only to AT', () => {
    const { element } = setup(true);
    const badge = element.querySelector('[data-testid="ai-companion-badge"]');
    expect(badge?.getAttribute('aria-label')).toContain('AI companion');
  });

  it('reacts when the disclosure resolves after first render', () => {
    const { fixture, element, stub } = setup(false);
    expect(element.querySelector('[data-testid="ai-companion-badge"]')).toBeNull();
    stub.disclosure.set(buildDisclosure());
    fixture.detectChanges();
    expect(element.querySelector('[data-testid="ai-companion-badge"]')).toBeTruthy();
  });

  it('has no critical/serious axe violations', async () => {
    const { fixture } = setup(true);
    const axe = (await import('axe-core')).default;
    const results = await axe.run(fixture.nativeElement);
    const serious = results.violations.filter(
      (v) => v.impact === 'critical' || v.impact === 'serious',
    );
    expect(serious.length).toBe(0);
  });
});
