/**
 * Storybook stories for AiTransparencyNoticeComponent (ADR-225).
 *
 * States: standard-audience notice, minor-audience variant, submitting (CTA
 * spinner), and a fail-loud acknowledge error (CTA stays enabled for retry).
 * The disclosure strings are BFF-served — a stubbed AiTransparencyService
 * supplies them so the stories render the exact governance copy.
 */
import type { Meta, StoryObj } from '@storybook/angular';
import { applicationConfig } from '@storybook/angular';
import { provideHttpClient } from '@angular/common/http';
import { signal } from '@angular/core';

import { AiTransparencyNoticeComponent } from './ai-transparency-notice.component';
import { AiTransparencyService } from '../../../core/services/ai-transparency.service';
import type {
  AiAcknowledgeState,
  AiDisclosure,
} from '../../../core/services/ai-transparency.model';

const DISCLOSURE_STANDARD: AiDisclosure = {
  version: '2026-07-07',
  locale: 'en',
  audienceVariant: 'standard',
  notice: {
    title: 'Meet your AI companion',
    body: 'Your Familiar is powered by AI. Its replies are generated and may be imperfect — always double-check anything important. You stay in control of your learning.',
    action: 'Got it',
  },
  badge: { label: 'AI companion', tooltip: 'Responses here are generated by AI.' },
  inlineLabels: {
    aiGenerated: { label: 'AI-generated', tooltip: 'Created by AI.' },
    aiAssisted: { label: 'AI-assisted', tooltip: 'Drafted with AI help.' },
    doseHeader: { label: 'AI-composed dose', tooltip: 'Composed by AI.' },
  },
};

const DISCLOSURE_MINOR: AiDisclosure = {
  ...DISCLOSURE_STANDARD,
  audienceVariant: 'minor',
  notice: {
    title: 'Say hi to your AI helper!',
    body: 'Your Familiar is a friendly AI. It thinks up its answers, so they can sometimes be wrong. Ask a grown-up or your teacher if you are not sure.',
    action: 'Okay!',
  },
};

function stub(opts: {
  disclosure: AiDisclosure;
  mustAck?: boolean;
  ackState?: AiAcknowledgeState;
}) {
  return {
    disclosure: signal(opts.disclosure),
    mustAcknowledge: signal(opts.mustAck ?? true),
    ackState: signal<AiAcknowledgeState>(opts.ackState ?? { status: 'idle' }),
    ensureLoaded: () => undefined,
    acknowledge: () => undefined,
    clearAckState: () => undefined,
  };
}

function providers(s: ReturnType<typeof stub>) {
  return applicationConfig({
    providers: [
      provideHttpClient(),
      { provide: AiTransparencyService, useValue: s },
    ],
  });
}

const meta: Meta<AiTransparencyNoticeComponent> = {
  title: 'Shared/AI Transparency/Notice',
  component: AiTransparencyNoticeComponent,
  parameters: {
    layout: 'fullscreen',
    a11y: { element: '#storybook-root' },
    docs: {
      description: {
        component:
          'ADR-225 one-time first-interaction NOTICE (EU AI Act Art 50). An ' +
          'acknowledgement — single "Got it", no decline/AI-off branch, not ' +
          'dismissible via backdrop or Escape.',
      },
    },
  },
};
export default meta;
type Story = StoryObj<AiTransparencyNoticeComponent>;

/** Standard adult-audience notice. */
export const Standard: Story = {
  decorators: [providers(stub({ disclosure: DISCLOSURE_STANDARD }))],
  name: 'Standard (adult)',
};

/** Minor-audience variant — simpler, safeguarding-oriented copy. */
export const MinorVariant: Story = {
  decorators: [providers(stub({ disclosure: DISCLOSURE_MINOR }))],
  name: 'Minor variant',
};

/** Submitting — CTA disabled with spinner while the acknowledge POSTs. */
export const Submitting: Story = {
  decorators: [
    providers(stub({ disclosure: DISCLOSURE_STANDARD, ackState: { status: 'submitting' } })),
  ],
};

/** Fail-loud acknowledge error — CTA stays enabled for retry. */
export const AcknowledgeError: Story = {
  decorators: [
    providers(
      stub({
        disclosure: DISCLOSURE_STANDARD,
        ackState: { status: 'error', error: 'core.ai_transparency.ack_error_unavailable' },
      }),
    ),
  ],
  name: 'Acknowledge error (retryable)',
};
